catalog_catalog_index:
    path:     /
    defaults: { _controller: "UniCatalogBundle:Catalog:index" }
    methods:  GET

catalog_catalog_show:
    path:     /{id}/show
    defaults: { _controller: "UniCatalogBundle:Catalog:show" }
    methods:  GET

catalog_catalog_new:
    path:     /new
    defaults: { _controller: "UniCatalogBundle:Catalog:new" }
    methods:  [GET, POST]

catalog_catalog_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniCatalogBundle:Catalog:edit" }
    methods:  [GET, POST]

catalog_catalog_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniCatalogBundle:Catalog:delete" }
    methods:  DELETE
