catalog_category_index:
    path:     /
    defaults: { _controller: "UniCatalogBundle:Category:index" }
    methods:  GET

catalog_category_show:
    path:     /{id}/show
    defaults: { _controller: "UniCatalogBundle:Category:show" }
    methods:  GET

catalog_category_new:
    path:     /new
    defaults: { _controller: "UniCatalogBundle:Category:new" }
    methods:  [GET, POST]

catalog_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniCatalogBundle:Category:edit" }
    methods:  [GET, POST]

catalog_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniCatalogBundle:Category:delete" }
    methods:  DELETE
