account_user_index:
    path:     /
    defaults: { _controller: "UniAccountBundle:User:index" }
    methods:  GET

account_user_show:
    path:     /{id}/show
    defaults: { _controller: "UniAccountBundle:User:show" }
    methods:  GET

account_user_new:
    path:     /new
    defaults: { _controller: "UniAccountBundle:User:new" }
    methods:  [GET, POST]

account_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAccountBundle:User:edit" }
    methods:  [GET, POST]

account_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAccountBundle:User:delete" }
    methods:  DELETE
