Uni\AdminBundle\Entity\Catalog:
    type: entity
    table: uni_catalog
    repositoryClass:  Uni\AdminBundle\Entity\CatalogRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        account:
            targetEntity: Uni\AdminBundle\Entity\Account
            inversedBy: catalogs
        page:
            targetEntity: Uni\AdminBundle\Entity\Page
            inversedBy: catalogs
    oneToMany:
        categories:
            targetEntity:  Uni\AdminBundle\Entity\Category
            mappedBy: catalog
            cascade: ['persist', 'merge']
    fields:
        name:
            type: string
            length: 100
            nullable: true
        slug:
          type: string
          length: 128
          gedmo:
            slug:
              separator: _
              style: lower
              fields:
                - name
        catalog_content:
            type: string
            length: 100
            nullable: true
        catalog_calltoaction:
            type: string
            length: 20
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deleted_at
            time_aware: false
    lifecycleCallbacks: {  }