Uni\AdminBundle\Entity\CatalogItem:
    type: entity
    table: uni_catalogitem
    repositoryClass: Uni\AdminBundle\Entity\CatalogItemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        account:
            targetEntity: Uni\AdminBundle\Entity\Account
            inversedBy: catalogitems
        subcategory:
            targetEntity: Uni\AdminBundle\Entity\Subcategory
            inversedBy: catalogitems
        product:
            targetEntity: Uni\AdminBundle\Entity\Product
            inversedBy: catalogitems
    fields:
        quantity:
            type: integer
            nullable: true
        discount:
            type: integer
            nullable: true
        surcharge:
            type: integer
            nullable: true
        price:
            type: integer
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deleted_at
            time_aware: false
    lifecycleCallbacks: {  }
