Uni\AdminBundle\Entity\Invoice:
    type: entity
    table: uni_invoice
    repositoryClass: Uni\AdminBundle\Entity\InvoiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: Uni\AdminBundle\Entity\User
            inversedBy: invoices
        account:
            targetEntity: Uni\AdminBundle\Entity\Account
            inversedBy: invoices
        order:
            targetEntity: Uni\AdminBundle\Entity\Order
            inversedBy: invoice
        paymentstatus:
            targetEntity: Uni\AdminBundle\Entity\PaymentStatus            
    oneToMany:
        actions:
            targetEntity: Uni\AdminBundle\Entity\InvoiceAction
            mappedBy: invoice
            cascade: ['remove']
        shipments:
            targetEntity: Uni\AdminBundle\Entity\Shipment
            mappedBy: invoice
    fields:
        name:
            type: string
            length: 100
            nullable: true
        number:
            type: string
            length: 100
            nullable: true
        amount:
            type: integer
            nullable: true
        filename:
            type: string
            length: 100
            nullable: true
        note:
            type: text
            nullable: true
        pay_in:
            type: datetime
        issued_at:
            type: datetime
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deleted_at
            time_aware: false
    lifecycleCallbacks: {  }
