Uni\AdminBundle\Entity\Issuer:
    type: entity
    table: uni_issuer
    repositoryClass: Uni\AdminBundle\Entity\IssuerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: Uni\AdminBundle\Entity\User
            inversedBy: issuers
        account:
            targetEntity: Uni\AdminBundle\Entity\Account
            inversedBy: issuers
        commune:
            targetEntity: Uni\AdminBundle\Entity\Commune
    oneToMany:
        budgets:
            targetEntity: Uni\AdminBundle\Entity\Budget
            mappedBy: issuer
    fields:
        name:
            type: string
            length: 100
            nullable: true
        image:
            type: string
            length: 100
            nullable: true
        rut:
            type: string
            length: 30
            nullable: true
        address_street:
            type: string
            length: 100
            nullable: true
        address_number:
            type: string
            length: 10
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deleted_at
            time_aware: false
    lifecycleCallbacks: {  }
