Uni\AdminBundle\Entity\Note:
    type: entity
    table: uni_note
    repositoryClass: Uni\AdminBundle\Entity\NoteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: Uni\AdminBundle\Entity\User
            inversedBy: notes
        account:
            targetEntity: Uni\AdminBundle\Entity\Account
            inversedBy: notes
    manyToMany:
        budgets:
            targetEntity: Uni\AdminBundle\Entity\Budget
            mappedBy: notes
    fields:
        name:
            type: string
            length: 100
        title:
            type: string
            length: 30
        description:
            type: text
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deleted_at
            time_aware: false
    lifecycleCallbacks: {  }
