Uni\AdminBundle\Entity\Page:
    type: entity
    table: uni_page
    repositoryClass:  Uni\AdminBundle\Entity\PageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        account:
            targetEntity: Uni\AdminBundle\Entity\Account
            inversedBy: pages
    oneToMany:
        features:
            targetEntity:  Uni\AdminBundle\Entity\Feature
            mappedBy: page
        links:
            targetEntity:  Uni\AdminBundle\Entity\Link
            mappedBy: page
        photographies:
            targetEntity:  Uni\AdminBundle\Entity\Photography
            mappedBy: page
            cascade: ['persist', 'merge', 'remove']
        socialmedia:
            targetEntity:  Uni\AdminBundle\Entity\Socialmedia
            mappedBy: page
        catalogs:
            targetEntity:  Uni\AdminBundle\Entity\Catalog
            mappedBy: page
    fields:
        name:
            type: string
            length: 100
            nullable: true
        domain:
            type: string
            length: 100
            nullable: true
        image:
            type: string
            length: 200
            nullable: true
        brand:
            type: string
            length: 100
            nullable: true
        brand_primary_color:
            type: string
            length: 10
            nullable: true
        brand_secondary_color:
            type: string
            length: 10
            nullable: true
        main_title:
            type: string
            length: 25
            nullable: true
        main_subtitle:
            type: string
            length: 100
            nullable: true
        main_calltoaction:
            type: string
            length: 20
            nullable: true
        about_title:
            type: string
            length: 20
            nullable: true
        about_content:
            type: text
            nullable: true
        feature_title:
            type: string
            length: 20
            nullable: true
        feature_content:
            type: text
            nullable: true
        link_title:
            type: string
            length: 40
            nullable: true
        socialmedia_title:
            type: string
            length: 20
            nullable: true
        contact_title:
            type: string
            length: 20
            nullable: true
        contact_content:
            type: text
            nullable: true
        contact_phone:
            type: string
            length: 20
            nullable: true
        contact_email:
            type: string
            length: 100
            nullable: true
        contact_address:
            type: string
            length: 100
            nullable: true
        contact_schedule:
            type: string
            length: 50
            nullable: true
        keywords:
            type: text
            nullable: true
        social_share_image:
            type: string
            length: 200
            nullable: true
        social_share_title:
            type: string
            length: 50
            nullable: true
        social_share_description:
            type: text
            nullable: true
        fb_share_appid:
            type: integer
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deleted_at
            time_aware: false
    lifecycleCallbacks: {  }