Uni\AdminBundle\Entity\Photography:
    type: entity
    table: uni_photography
    repositoryClass: Uni\AdminBundle\Entity\PhotographyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        account:
            targetEntity: Uni\AdminBundle\Entity\Account
            inversedBy: photographies
        page:
            targetEntity: Uni\AdminBundle\Entity\Page
            inversedBy: photographies
    fields:
        image:
            type: string
            length: 200

        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deleted_at
            time_aware: false
    lifecycleCallbacks: {  }
