Uni\AdminBundle\Entity\PortfolioItem:
    type: entity
    table: uni_portfolioitem
    repositoryClass: Uni\AdminBundle\Entity\PortfolioItemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: Uni\AdminBundle\Entity\User
            inversedBy: portfolioitems
        account:
            targetEntity: Uni\AdminBundle\Entity\Account
            inversedBy: portfolioitems
        portfoliocategory:
            targetEntity: Uni\AdminBundle\Entity\PortfolioCategory
            inversedBy: portfolioitems
        document:
            targetEntity: Uni\AdminBundle\Entity\Document
            inversedBy: portfolioitems
    fields:
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deleted_at
            time_aware: false
    lifecycleCallbacks: {  }
