Uni\AdminBundle\Entity\PortfolioCategory:
    type: entity
    table: uni_portfoliocategory
    repositoryClass:  Uni\AdminBundle\Entity\PortfolioCategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        account:
            targetEntity: Uni\AdminBundle\Entity\Account
            inversedBy: portfolios
        portfolio:
            targetEntity: Uni\AdminBundle\Entity\Portfolio
            inversedBy: portfoliocategories
    oneToMany:
        portfolioitems:
            targetEntity: Uni\AdminBundle\Entity\PortfolioItem
            mappedBy: portfoliocategory
    fields:
        name:
            type: string
            length: 100
            nullable: true
        slug:
          type: string
          length: 128
          gedmo:
            slug:
              separator: _
              style: lower
              fields:
                - name
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deleted_at
            time_aware: false
    lifecycleCallbacks: {  }