# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~
        less:
            node: %node_bin_path%
            node_paths: [%node_lib_path%]
    read_from: %kernel.root_dir%/..
    write_to: %kernel.root_dir%/..
    assets:
        uni_admin_css:
            inputs:
                - src/Uni/AdminBundle/Resources/less/build.less
            filters:
                - less
                - cssrewrite
            output: src/Uni/AdminBundle/Resources/public/css/admin.css
        uni_user_css:
            inputs:
                - src/Uni/UserBundle/Resources/less/build.less
            filters:
                - less
                - cssrewrite
            output: src/Uni/UserBundle/Resources/public/css/user.css
        uni_offer_css:
            inputs:
                - src/Uni/OfferBundle/Resources/less/build.less
            filters:
                - less
                - cssrewrite
            output: src/Uni/OfferBundle/Resources/public/css/offer.css
        uni_page_css:
            inputs:
                - src/Uni/PageBundle/Resources/less/build.less
            filters:
                - less
                - cssrewrite
            output: src/Uni/PageBundle/Resources/public/css/page.css
        uni_offerexport_css:
            inputs:
                - src/Uni/OfferBundle/Resources/less/export/build.less
            filters:
                - less
                - cssrewrite
            output: src/Uni/OfferBundle/Resources/public/css/offerexport.css
        uni_controlpanel_css:
            inputs:
                - src/Uni/ControlPanelBundle/Resources/less/build.less
            filters:
                - less
                - cssrewrite
            output: src/Uni/ControlPanelBundle/Resources/public/css/controlpanel.css
        uni_public_css:
            inputs:
                - src/Uni/PublicBundle/Resources/less/build.less
            filters:
                - less
                - cssrewrite
            output: src/Uni/PublicBundle/Resources/public/css/public.css
        uni_public_catalog_css:
            inputs:
                - src/Uni/PublicBundle/Resources/less/build-catalog.less
            filters:
                - less
                - cssrewrite
            output: src/Uni/PublicBundle/Resources/public/css/public-catalog.css
        uni_public_portfolio_css:
            inputs:
                - src/Uni/PublicBundle/Resources/less/build-portfolio.less
            filters:
                - less
                - cssrewrite
            output: src/Uni/PublicBundle/Resources/public/css/public-portfolio.css
#        frontend_css:
#            inputs:
#                - src/Uni/OfferBundle/Resources/less/build.less
#            filters:
#                - less
#                - cssrewrite
#            output: src/Uni/OfferBundle/Resources/public/css/offer.css
