# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~
        less:
            node: %node_bin_path%
            node_paths: [%node_lib_path%]
    read_from: %kernel.root_dir%/..
    write_to: %kernel.root_dir%/..
    assets:
        uni_admin_css:
            inputs:
                - src/Uni/AdminBundle/Resources/less/build.less
            filters:
                - less
                - cssrewrite
            output: src/Uni/AdminBundle/Resources/public/css/admin.css
        uni_user_css:
            inputs:
                - src/Uni/UserBundle/Resources/less/build.less
            filters:
                - less
                - cssrewrite
            output: src/Uni/UserBundle/Resources/public/css/user.css
        uni_agent_css:
            inputs:
                - src/Uni/AgentBundle/Resources/less/build.less
            filters:
                - less
                - cssrewrite
            output: src/Uni/AgentBundle/Resources/public/css/agent.css
        uni_agentexport_css:
            inputs:
                - src/Uni/AgentBundle/Resources/less/export/build.less
            filters:
                - less
                - cssrewrite
            output: src/Uni/AgentBundle/Resources/public/css/agentexport.css
#        frontend_css:
#            inputs:
#                - src/Uni/AgentBundle/Resources/less/build.less
#            filters:
#                - less
#                - cssrewrite
#            output: src/Uni/AgentBundle/Resources/public/css/agent.css
