fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Uni\AdminBundle\Entity\User
    use_listener:               true
    use_username_form_type:     true
    model_manager_name:         null

    service:
        mailer:                 fos_user.mailer.default
        email_canonicalizer:    fos_user.util.canonicalizer.default
        username_canonicalizer: fos_user.util.canonicalizer.default
        token_generator:        fos_user.util.token_generator.default
        user_manager:           fos_user.user_manager.default

    from_email:
        address: contacto@unisign.cl
        sender_name: Equipo de uniSign

    registration:
        form:
            type: Uni\UserBundle\Form\RegistrationType
        confirmation:
            enabled:            true
            from_email:
                address: registro@unisign.cl
                sender_name: Equipo de uniSign

    resetting:
        form:
            type: Uni\UserBundle\Form\ResettingType
        token_ttl: 86400
        email:
            from_email:
                address: recuperacion@unisign.cl
                sender_name: Equipo de uniSign

    group:
        group_class: Uni\AdminBundle\Entity\Group
        form:
            type: Uni\UserBundle\Form\GroupType

    change_password:
        form:
            type: Uni\UserBundle\Form\ChangePasswordType

    profile:
        form:
            type: Uni\UserBundle\Form\ProfileType
