liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        main_photography:
            quality: 75
            filters:
                upscale: { min: [1920, 1080] }
                thumbnail: { size: [1366, 900], mode: inset }
        main_photography_small:
            quality: 75
            filters:
                upscale: { min: [160, 120] }
                thumbnail: { size: [160, 120], mode: inset }
        product_export_small:
            quality: 75
            filters:
                upscale: { min: [120, 120] }
                thumbnail: { size: [120, 120], mode: inset }
        product_image_large:
            quality: 75
            filters:
                upscale: { min: [900, 900] }
                thumbnail: { size: [900, 900], mode: outbound }
        product_image:
            quality: 75
            filters:
                upscale: { min: [900, 900] }
                thumbnail: { size: [900, 900], mode: outbound }        
        product_image_small:
            quality: 75
            filters:
                upscale: { min: [120, 120] }
                thumbnail: { size: [120, 120], mode: outbound }
        product_show_medium:
            quality: 75
            filters:
                upscale: { min: [400, 400] }
                thumbnail: { size: [400, 400], mode: inset }
        product_edit_preview:
            quality: 75
            filters:
                upscale: { min: [256, 160] }
                thumbnail: { size: [256, 160], mode: inset }

        document_image_small:
            quality: 75
            filters:
                upscale: { min: [120, 120] }
                thumbnail: { size: [120, 120], mode: outbound }

        document_image:
            quality: 75
            filters:
                upscale: { min: [900, 900] }
                thumbnail: { size: [900, 900], mode: outbound }

        issuer_export_small:
            quality: 75
            filters:
                upscale: { min: [120, 120] }
                thumbnail: { size: [120, 120], mode: inset }
        issuer_export_medium:
            quality: 75
            filters:
                upscale: { min: [240, 120] }
                thumbnail: { size: [240, 120], mode: inset }
        issuer_preview_small:
            quality: 75
            filters:
                upscale: { min: [256, 160] }
                thumbnail: { size: [256, 160], mode: inset }

        brand_photography:
            quality: 75
            filters:
                upscale: { min: [200] }
                thumbnail: { size: [200], mode: outbound }
        brand_photography_edit_preview:
            quality: 75
            filters:
                upscale: { min: [256, 160] }
                thumbnail: { size: [256, 160], mode: inset }
        brand_photography_catalog:
            quality: 75
            filters:
                upscale: { min: [120] }
                thumbnail: { size: [120], mode: outbound }

        feature_edit_preview:
            quality: 75
            filters:
                upscale: { min: [256, 160] }
                thumbnail: { size: [256, 160], mode: inset }
        feature_image_small:
            quality: 75
            filters:
                upscale: { min: [120, 120] }
                thumbnail: { size: [120, 120], mode: outbound }
        feature_image:
            quality: 75
            filters:
                upscale: { min: [800, 600] }
                thumbnail: { size: [800, 600], mode: outbound }
        feature_image_large:
            quality: 75
            filters:
                upscale: { min: [1366, 768] }
                thumbnail: { size: [1366, 768], mode: outbound }

        photography_image_small:
            quality: 75
            filters:
                upscale: { min: [120, 120] }
                thumbnail: { size: [120, 120], mode: outbound }
        photography_index_small:
            quality: 75
            filters:
                upscale: { min: [192, 108] }
                thumbnail: { size: [192, 108], mode: outbound }

        team_index_small:
            quality: 75
            filters:
                upscale: { min: [192, 108] }
                thumbnail: { size: [192, 108], mode: outbound }
        team_image:
            quality: 75
            filters:
                upscale: { min: [225, 225] }
                thumbnail: { size: [225, 225], mode: outbound }
