parameters:
    roles:
        ROLE_USER: role.user
        ROLE_PAGE: role.page
        ROLE_CATALOG: role.catalog
        ROLE_PORTFOLIO: role.portfolio
        ROLE_OFFER: role.offer
        ROLE_LEADER: role.leader
        ROLE_ADMIN: role.admin