parameters:
    roles:
        ROLE_USER: role.user
        ROLE_PAGE: role.page
        ROLE_CATALOG: role.catalog
        ROLE_BUDGET: role.budget
        ROLE_LEADER: role.leader
        ROLE_ADMIN: role.admin
