_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

uni_admin:
    resource: "@UniAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

uni_offer:
    resource: "@UniOfferBundle/Resources/config/routing.yml"
    prefix:   /offer

uni_user:
    resource: "@UniUserBundle/Resources/config/routing.yml"
    prefix:   /user

uni_catalog:
    resource: "@UniCatalogBundle/Resources/config/routing.yml"
    prefix:   /catalog

uni_page:
    resource: "@UniPageBundle/Resources/config/routing.yml"
    prefix:   /page

uni_controlpanel:
    resource: "@UniControlPanelBundle/Resources/config/routing.yml"
    prefix:   /controlpanel

uni_public:
    resource: "@UniPublicBundle/Resources/config/routing.yml"
    prefix:   /

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: fos_user_security_login
        permanent: true