_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

uni_account:
    resource: "@UniAccountBundle/Resources/config/routing.yml"
    prefix:   /backend/account

uni_admin:
    resource: "@UniAdminBundle/Resources/config/routing.yml"
    prefix:   /backend/admin

uni_offer:
    resource: "@UniOfferBundle/Resources/config/routing.yml"
    prefix:   /backend/offer

uni_user:
    resource: "@UniUserBundle/Resources/config/routing.yml"
    prefix:   /backend/user

uni_catalog:
    resource: "@UniCatalogBundle/Resources/config/routing.yml"
    prefix:   /backend/catalog

uni_page:
    resource: "@UniPageBundle/Resources/config/routing.yml"
    prefix:   /backend/page

uni_controlpanel:
    resource: "@UniControlPanelBundle/Resources/config/routing.yml"
    prefix:   /backend/controlpanel

uni_public:
    resource: "@UniPublicBundle/Resources/config/routing.yml"
    prefix:   /

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: fos_user_security_login
        permanent: true