vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    default_filename_attribute_suffix:  _name
    storage: file_system
    twig: true
    metadata:
        cache: file
        file_cache:
            dir: '%kernel.cache_dir%/vich_uploader'
        auto_detection: true
    mappings:
        main_photography:
            uri_prefix: uploads/mainphotography
            upload_destination: %kernel.root_dir%/../web/uploads/mainphotography
            namer: vich_uploader.namer_origname
        product_image:
            uri_prefix: uploads/product
            upload_destination: %kernel.root_dir%/../web/uploads/product
            namer: vich_uploader.namer_origname
        issuer_image:
            uri_prefix: uploads/issuer
            upload_destination: %kernel.root_dir%/../web/uploads/issuer
            namer: vich_uploader.namer_origname
        feature_image:
            uri_prefix: uploads/feature
            upload_destination: %kernel.root_dir%/../web/uploads/feature
            namer: vich_uploader.namer_origname

        order_file:
            uri_prefix: uploads/order
            upload_destination: %kernel.root_dir%/../web/uploads/order
            namer: vich_uploader.namer_origname
        invoice_file:
            uri_prefix: uploads/invoice
            upload_destination: %kernel.root_dir%/../web/uploads/invoice
            namer: vich_uploader.namer_origname
        shipment_file:
            uri_prefix: uploads/shipment
            upload_destination: %kernel.root_dir%/../web/uploads/shipment
            namer: vich_uploader.namer_origname

