uni_agent_issuer:
    resource: "@UniAgentBundle/Resources/config/routing/issuer.yml"
    prefix:   /issuer

uni_agent_account:
    resource: "@UniAgentBundle/Resources/config/routing/account.yml"
    prefix:   /account

uni_agent_user:
    resource: "@UniAgentBundle/Resources/config/routing/user.yml"
    prefix:   /user

uni_agent_test:
    resource: "@UniAgentBundle/Resources/config/routing/test.yml"
    prefix:   /test

uni_agent_budget:
    resource: "@UniAgentBundle/Resources/config/routing/budget.yml"
    prefix:   /budget

uni_agent_client:
    resource: "@UniAgentBundle/Resources/config/routing/client.yml"
    prefix:   /client

uni_agent_item:
    resource: "@UniAgentBundle/Resources/config/routing/item.yml"
    prefix:   /item

uni_agent_product:
    resource: "@UniAgentBundle/Resources/config/routing/product.yml"
    prefix:   /product

uni_agent_provider:
    resource: "@UniAgentBundle/Resources/config/routing/provider.yml"
    prefix:   /provider

uni_agent_seller:
    resource: "@UniAgentBundle/Resources/config/routing/seller.yml"
    prefix:   /seller

uni_agent_note:
    resource: "@UniAgentBundle/Resources/config/routing/note.yml"
    prefix:   /note

uni_agent_search:
    resource: "@UniAgentBundle/Resources/config/routing/search.yml"
    prefix:   /search

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

uni_agent_root:
    resource: "@UniAgentBundle/Resources/config/routing/root.yml"
    prefix:   /
