controlpanel_account_show:
    path:     /{id}/show
    defaults: { _controller: "UniControlPanelBundle:Account:show" }
    methods:  GET

controlpanel_account_edit:
    path:     /edit
    defaults: { _controller: "UniControlPanelBundle:Account:edit" }
    methods:  [GET, POST]
