controlpanel_socialmedia_index:
    path:     /
    defaults: { _controller: "UniControlPanelBundle:Socialmedia:index" }
    methods:  GET

controlpanel_socialmedia_show:
    path:     /{id}/show
    defaults: { _controller: "UniControlPanelBundle:Socialmedia:show" }
    methods:  GET

controlpanel_socialmedia_new:
    path:     /new
    defaults: { _controller: "UniControlPanelBundle:Socialmedia:new" }
    methods:  [GET, POST]

controlpanel_socialmedia_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniControlPanelBundle:Socialmedia:edit" }
    methods:  [GET, POST]

controlpanel_socialmedia_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniControlPanelBundle:Socialmedia:delete" }
    methods:  DELETE
