controlpanel_subcategory_index:
    path:     /
    defaults: { _controller: "UniControlPanelBundle:Subcategory:index" }
    methods:  GET

controlpanel_subcategory_show:
    path:     /{id}/show
    defaults: { _controller: "UniControlPanelBundle:Subcategory:show" }
    methods:  GET

controlpanel_subcategory_new:
    path:     /new
    defaults: { _controller: "UniControlPanelBundle:Subcategory:new" }
    methods:  [GET, POST]

controlpanel_subcategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniControlPanelBundle:Subcategory:edit" }
    methods:  [GET, POST]

controlpanel_subcategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniControlPanelBundle:Subcategory:delete" }
    methods:  DELETE
