services:
#    validator.existe_rut:
#        class: Uni\AdminBundle\Validator\Constraints\ExisteRutValidator
#        arguments: [@doctrine.orm.entity_manager]
#        tags:
#            - { name: validator.constraint_validator, alias: existe_rut }
#    uni_admin.example:
#        class: Uni\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
