uni_catalog_dashboard:
    resource: "@UniCatalogBundle/Resources/config/routing/dashboard.yml"
    prefix:   /dashboard

uni_catalog_catalog:
    resource: "@UniCatalogBundle/Resources/config/routing/catalog.yml"
    prefix:   /catalog

uni_catalog_category:
    resource: "@UniCatalogBundle/Resources/config/routing/category.yml"
    prefix:   /category

uni_catalog_subcategory:
    resource: "@UniCatalogBundle/Resources/config/routing/subcategory.yml"
    prefix:   /subcategory

uni_catalog_product:
    resource: "@UniCatalogBundle/Resources/config/routing/product.yml"
    prefix:   /product

uni_catalog_catalogitem:
    resource: "@UniCatalogBundle/Resources/config/routing/catalogitem.yml"
    prefix:   /catalogitem

uni_catalog_root:
    resource: "@UniCatalogBundle/Resources/config/routing/root.yml"
    prefix:   /

#test
uni_catalog_catalogtest:
    resource: "@UniCatalogBundle/Resources/config/routing/catalogtest.yml"
    prefix:   /catalogtest

uni_catalog_catalogcategorytest:
    resource: "@UniCatalogBundle/Resources/config/routing/catalogcategorytest.yml"
    prefix:   /catalogcategorytest

uni_catalog_catalogsubcategorytest:
    resource: "@UniCatalogBundle/Resources/config/routing/catalogsubcategorytest.yml"
    prefix:   /catalogsubcategorytest

uni_catalog_catalogitemtest:
    resource: "@UniCatalogBundle/Resources/config/routing/catalogitemtest.yml"
    prefix:   /catalogitemtest