uni_catalog_dashboard:
    resource: "@UniCatalogBundle/Resources/config/routing/dashboard.yml"
    prefix:   /dashboard

uni_catalog_catalog:
    resource: "@UniCatalogBundle/Resources/config/routing/catalog.yml"
    prefix:   /catalog

uni_catalog_category:
    resource: "@UniCatalogBundle/Resources/config/routing/category.yml"
    prefix:   /category

uni_catalog_subcategory:
    resource: "@UniCatalogBundle/Resources/config/routing/subcategory.yml"
    prefix:   /subcategory

uni_catalog_product:
    resource: "@UniCatalogBundle/Resources/config/routing/product.yml"
    prefix:   /product

uni_catalog_catalogitem:
    resource: "@UniCatalogBundle/Resources/config/routing/catalogitem.yml"
    prefix:   /catalogitem

uni_catalog_root:
    resource: "@UniCatalogBundle/Resources/config/routing/root.yml"
    prefix:   /