services:
#    uni_catalog.example:
#        class: Uni\CatalogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    uni_page.form.catalogitem:
        class: Uni\CatalogBundle\Form\CatalogItemType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type, alias: uni_catalogbundle_catalogitem }