agent_issuer_index:
    path:     /
    defaults: { _controller: "UniAgentBundle:Issuer:index" }
    methods:  GET

agent_issuer_show:
    path:     /{id}/show
    defaults: { _controller: "UniAgentBundle:Issuer:show" }
    methods:  GET

agent_issuer_new:
    path:     /new
    defaults: { _controller: "UniAgentBundle:Issuer:new" }
    methods:  [GET, POST]

agent_issuer_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAgentBundle:Issuer:edit" }
    methods:  [GET, POST]

agent_issuer_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAgentBundle:Issuer:delete" }
    methods:  DELETE
