agent_test_index:
    path:     /
    defaults: { _controller: "UniAgentBundle:Test:index" }
    methods:  GET

agent_test_show:
    path:     /{id}/show
    defaults: { _controller: "UniAgentBundle:Test:show" }
    methods:  GET

agent_test_export:
    path:     /{id}/export
    defaults: { _controller: "UniAgentBundle:Test:export" }
    methods:  GET

agent_test_pdf:
    path:     /{id}/pdf
    defaults: { _controller: "UniAgentBundle:Test:pdf" }
    methods:  GET

agent_test_new:
    path:     /new
    defaults: { _controller: "UniAgentBundle:Test:new" }
    methods:  [GET, POST]

agent_test_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAgentBundle:Test:edit" }
    methods:  [GET, POST]

agent_test_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAgentBundle:Test:delete" }
    methods:  DELETE
