agent_user_index:
    path:     /index
    defaults: { _controller: "UniAgentBundle:User:index" }
    methods:  GET

agent_user_show:
    path:     /{id}/show
    defaults: { _controller: "UniAgentBundle:User:show" }
    methods:  GET

agent_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAgentBundle:User:edit" }
    methods:  [GET, POST]

agent_user_change_password:
    path:     /changepassword
    defaults: { _controller: "UniAgentBundle:User:changepassword" }
    methods:  [GET, POST]

agent_user_register:
    path:     /register
    defaults: { _controller: "UniAgentBundle:User:register" }
    methods:  [GET, POST]

agent_user_check_email:
    path:     /check-email
    defaults: { _controller: "UniAgentBundle:User:checkEmail" }
    methods:  GET
