<?php

namespace Uni\AdminBundle\Entity;

/**
 * AccountPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountPaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
