<?php

namespace Uni\AdminBundle\Entity;

/**
 * CatalogItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCatalog($catalog)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('ci')
            ->from('UniAdminBundle:CatalogItem', 'ci')
            ->join('ci.subcategory', 'cis')
            ->join('cis.category', 'cisc')
            ->join('cisc.catalog', 'ciscc')
            ->where('ciscc.id = :catalog')
            ->setParameter('catalog', $catalog)
        ;
        return $qb->getQuery()->getResult();
    }
}
