<?php

namespace Uni\AdminBundle\Entity;

/**
 * InvoiceActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceActionRepository extends \Doctrine\ORM\EntityRepository
{
}
