<?php

namespace Uni\AdminBundle\Entity;

/**
 * PortfolioTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioTagRepository extends \Doctrine\ORM\EntityRepository
{
}
