<?php

namespace Uni\AdminBundle\Entity;

/**
 * PortfolioCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
