<?php

namespace Uni\AdminBundle\Entity;

/**
 * PortfolioItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPortfolio($portfolio)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('pi')
            ->from('UniAdminBundle:PortfolioItem', 'pi')
            ->join('pi.portfoliocategory', 'pipc')
            ->join('pipc.portfolio', 'pipcp')
            ->where('pipcp.id = :portfolio')
            ->setParameter('portfolio', $portfolio)
        ;
        return $qb->getQuery()->getResult();
    }  
}