<?php

namespace Uni\AdminBundle\Entity;

/**
 * SocialmediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialmediaRepository extends \Doctrine\ORM\EntityRepository
{
}
