offer_item_index:
    path:     /
    defaults: { _controller: "UniOfferBundle:Item:index" }
    methods:  GET

offer_item_show:
    path:     /{id}/show
    defaults: { _controller: "UniOfferBundle:Item:show" }
    methods:  GET

offer_item_new:
    path:     /new
    defaults: { _controller: "UniOfferBundle:Item:new" }
    methods:  [GET, POST]

offer_item_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniOfferBundle:Item:edit" }
    methods:  [GET, POST]

offer_item_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniOfferBundle:Item:delete" }
    methods:  DELETE
