offer_note_index:
    path:     /
    defaults: { _controller: "UniOfferBundle:Note:index" }
    methods:  GET

offer_note_show:
    path:     /{id}/show
    defaults: { _controller: "UniOfferBundle:Note:show" }
    methods:  GET

offer_note_new:
    path:     /new
    defaults: { _controller: "UniOfferBundle:Note:new" }
    methods:  [GET, POST]

offer_note_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniOfferBundle:Note:edit" }
    methods:  [GET, POST]

offer_note_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniOfferBundle:Note:delete" }
    methods:  DELETE
