offer_product_index:
    path:     /
    defaults: { _controller: "UniOfferBundle:Product:index" }
    methods:  GET

offer_product_show:
    path:     /{id}/show
    defaults: { _controller: "UniOfferBundle:Product:show" }
    methods:  GET

offer_product_new:
    path:     /new
    defaults: { _controller: "UniOfferBundle:Product:new" }
    methods:  [GET, POST]

offer_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniOfferBundle:Product:edit" }
    methods:  [GET, POST]

offer_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniOfferBundle:Product:delete" }
    methods:  DELETE

offer_product_search_cm:
    path:     /searchcm
    defaults: { _controller: "UniOfferBundle:Product:searchcm" }
    methods:  GET
