offer_search_product_name:
    path:     /product/name
    defaults: { _controller: "UniOfferBundle:Search:productName" }
    methods:  GET

offer_search_product_cm:
    path:     /product/cm
    defaults: { _controller: "UniOfferBundle:Search:productCm" }
    methods:  GET
