admin_catalogitem_index:
    path:     /
    defaults: { _controller: "UniAdminBundle:CatalogItem:index" }
    methods:  GET

admin_catalogitem_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:CatalogItem:show" }
    methods:  GET

admin_catalogitem_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:CatalogItem:new" }
    methods:  [GET, POST]

admin_catalogitem_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:CatalogItem:edit" }
    methods:  [GET, POST]

admin_catalogitem_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:CatalogItem:delete" }
    methods:  DELETE
