admin_group_index:
    path:     /
    defaults: { _controller: "UniAdminBundle:Group:index" }
    methods:  GET

admin_group_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:Group:show" }
    methods:  GET

admin_group_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:Group:new" }
    methods:  [GET, POST]

admin_group_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:Group:edit" }
    methods:  [GET, POST]

admin_group_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:Group:delete" }
    methods:  DELETE
