admin_page_index:
    path:     /
    defaults: { _controller: "UniAdminBundle:Page:index" }
    methods:  GET

admin_page_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:Page:show" }
    methods:  GET

admin_page_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:Page:new" }
    methods:  [GET, POST]

admin_page_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:Page:edit" }
    methods:  [GET, POST]

admin_page_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:Page:delete" }
    methods:  DELETE
