admin_productpackage_index:
    path:     /
    defaults: { _controller: "UniAdminBundle:ProductPackage:index" }
    methods:  GET

admin_productpackage_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:ProductPackage:show" }
    methods:  GET

admin_productpackage_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:ProductPackage:new" }
    methods:  [GET, POST]

admin_productpackage_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:ProductPackage:edit" }
    methods:  [GET, POST]

admin_productpackage_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:ProductPackage:delete" }
    methods:  DELETE
