admin_province_index:
    path:     /
    defaults: { _controller: "UniAdminBundle:Province:index" }
    methods:  GET

admin_province_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:Province:show" }
    methods:  GET

admin_province_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:Province:new" }
    methods:  [GET, POST]

admin_province_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:Province:edit" }
    methods:  [GET, POST]

admin_province_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:Province:delete" }
    methods:  DELETE
