admin_shipment_index:
    path:     /
    defaults: { _controller: "UniAdminBundle:Shipment:index" }
    methods:  GET

admin_shipment_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:Shipment:show" }
    methods:  GET

admin_shipment_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:Shipment:new" }
    methods:  [GET, POST]

admin_shipment_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:Shipment:edit" }
    methods:  [GET, POST]

admin_shipment_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:Shipment:delete" }
    methods:  DELETE
