admin_socialmedia_index:
    path:     /
    defaults: { _controller: "UniAdminBundle:SocialMedia:index" }
    methods:  GET

admin_socialmedia_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:SocialMedia:show" }
    methods:  GET

admin_socialmedia_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:SocialMedia:new" }
    methods:  [GET, POST]

admin_socialmedia_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:SocialMedia:edit" }
    methods:  [GET, POST]

admin_socialmedia_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:SocialMedia:delete" }
    methods:  DELETE
